repos:
  - repo: local
    hooks:
      - id: gofumpt
        name: run gofumpt
        entry: ./bin/gofumpt -l -w .
        language: system
        pass_filenames: false

      - id: golangci-lint
        name: run golangci-lint
        entry: ./bin/golangci-lint run ./...
        language: system
        pass_filenames: false